name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm exec prettier --check .
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run type-check
